// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFNu5MUugM4xTSLePDbzjRzkDWdsjx0g8',
    appId: '1:48374136555:web:62cfd1b973f39a445cc8ae',
    messagingSenderId: '48374136555',
    projectId: 'pupzy-app-5f707',
    authDomain: 'pupzy-app-5f707.firebaseapp.com',
    storageBucket: 'pupzy-app-5f707.firebasestorage.app',
    measurementId: 'G-TRJ4PPPE2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHOJUrXQWayBW0v9pMfE0wo6lWrY8fz3Y',
    appId: '1:48374136555:android:771759429f522ce35cc8ae',
    messagingSenderId: '48374136555',
    projectId: 'pupzy-app-5f707',
    storageBucket: 'pupzy-app-5f707.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlCH-MLNACbFcJFf4pxxl8Ma31D1Oj91I',
    appId: '1:48374136555:ios:eec39fc56ad1a5c65cc8ae',
    messagingSenderId: '48374136555',
    projectId: 'pupzy-app-5f707',
    storageBucket: 'pupzy-app-5f707.firebasestorage.app',
    iosClientId: '48374136555-t9kh4nrdpaneun0g6uf1on2cs01610pt.apps.googleusercontent.com',
    iosBundleId: 'com.example.pupzy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlCH-MLNACbFcJFf4pxxl8Ma31D1Oj91I',
    appId: '1:48374136555:ios:eec39fc56ad1a5c65cc8ae',
    messagingSenderId: '48374136555',
    projectId: 'pupzy-app-5f707',
    storageBucket: 'pupzy-app-5f707.firebasestorage.app',
    iosClientId: '48374136555-t9kh4nrdpaneun0g6uf1on2cs01610pt.apps.googleusercontent.com',
    iosBundleId: 'com.example.pupzy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFNu5MUugM4xTSLePDbzjRzkDWdsjx0g8',
    appId: '1:48374136555:web:c10ff4bba8afba585cc8ae',
    messagingSenderId: '48374136555',
    projectId: 'pupzy-app-5f707',
    authDomain: 'pupzy-app-5f707.firebaseapp.com',
    storageBucket: 'pupzy-app-5f707.firebasestorage.app',
    measurementId: 'G-E3JE3963EW',
  );
}
