// k6/lib/auth.js
// Firebase ID token pool, shared across all VUs via SharedArray.
//
// SharedArray is read-only and initialised once at the start of the test run.
// It is shared in memory across VUs — no per-VU copies.
//
// Usage:
//   import { getToken } from './lib/auth.js';
//   const token = getToken(); // stable token for this VU

import { SharedArray } from 'k6/data';

// The `open()` call happens at module-init time (before VUs start).
// SharedArray ensures the file is parsed only once regardless of VU count.
const tokenPool = new SharedArray('firebase-tokens', function () {
  // tokens.json is generated by:
  // node --env-file=.env scripts/generate-tokens.mjs
  return JSON.parse(open('../tokens.json'));
});

/**
 * Returns a stable Firebase ID token for the current VU.
 *
 * Each VU gets a dedicated token (round-robin across the pool).
 * No race conditions — __VU is a read-only integer unique per virtual user.
 *
 * @returns {string} Firebase ID token
 */
export function getToken() {
  const index = (__VU - 1) % tokenPool.length;
  return tokenPool[index].idToken;
}

/**
 * Returns the full token entry: { uid, idToken, refreshToken, expiresAt }.
 * Useful if you need the uid for assertions or the refreshToken for soak tests.
 *
 * @returns {{ uid: string, idToken: string, refreshToken: string, expiresAt: number }}
 */
export function getTokenEntry() {
  const index = (__VU - 1) % tokenPool.length;
  return tokenPool[index];
}

/** Total number of tokens in the pool (useful for sanity checks). */
export const TOKEN_COUNT = tokenPool.length;
