/**
 * GqlContext — the typed object available in every GraphQL resolver via @Context().
 *
 * Populated by GraphQLModule's context factory in app.module.ts,
 * and enriched by:
 *  - FirebaseAuthGuard → attaches `user`
 *  - LoggingInterceptor → attaches `requestId`
 *  - createDataLoaders() → attaches `loaders` (per-request DataLoader instances)
 */
import type { Request } from 'express';
import type { User } from '../../database/schema';
import type { DataLoaders } from '../dataloaders/dataloaders.interface';

export interface GqlContext {
  /** Raw Express request. Available on every request. */
  req: Request;
  /**
   * The authenticated Pupzy user resolved from the Firebase ID token.
   * Undefined on @Public() routes (unauthenticated endpoints).
   */
  user?: User;
  /**
   * Unique ID for this request, generated by LoggingInterceptor.
   * Used for log correlation across resolvers and services.
   */
  requestId?: string;
  /**
   * Per-request DataLoader instances.
   * Created fresh for every request to avoid cross-request cache pollution.
   * Use these in field resolvers to batch DB lookups and avoid N+1 queries.
   */
  loaders: DataLoaders;
}
