export const ENUMS = {
  postType: ["RESCUE", "LOST", "ADOPTION", "PRODUCT", "MATING"],
  lostFoundType: ["LOST_PET", "FOUND_STRAY"],
  postStatus: ["ACTIVE", "RESOLVED", "REUNITED", "ADOPTED", "SOLD", "REMOVED"],
  moderationStatus: ["PENDING_AUTO_REVIEW", "CLEAN", "FLAGGED"],
  urgencyTier: ["CRITICAL", "URGENT", "MODERATE"],
  speciesType: ["DOG", "CAT", "BIRD", "RABBIT", "OTHER"],
  genderType: ["MALE", "FEMALE", "UNKNOWN"],
  ageUnit: ["DAYS", "WEEKS", "MONTHS", "YEARS"],
  reporterRole: ["REPORTING", "ON_SITE", "CAN_TRANSPORT"],
  foundAnimalCondition: ["HEALTHY", "INJURED", "UNKNOWN"],
  spaceRequirement: ["APARTMENT_OK", "NEEDS_YARD", "NEEDS_FARM_OR_LARGE_SPACE"],
  livingSituation: ["APARTMENT", "HOUSE_WITH_YARD", "FARM", "OTHER"],
  productCategory: [
    "CARE",
    "FOOD",
    "TRANSPORT",
    "ACCESSORIES",
    "GROOMING",
    "MEDICAL_SUPPLIES",
    "OTHER",
  ],
  productCondition: ["NEW", "LIKE_NEW", "USED"],
  requestStatus: ["PENDING", "APPROVED", "REJECTED"],
  reportReason: [
    "UNRELATED_TO_ANIMALS",
    "SPAM",
    "INAPPROPRIATE_CONTENT",
    "SCAM",
    "DUPLICATE",
    "OTHER",
  ],
  notificationType: [
    "NEW_UPVOTE",
    "POST_SAVED",
    "CONTACT_REQUEST_RECEIVED",
    "CONTACT_REQUEST_APPROVED",
    "CONTACT_REQUEST_REJECTED",
    "ADOPTION_APPLICATION_RECEIVED",
    "ADOPTION_APPLICATION_APPROVED",
    "ADOPTION_APPLICATION_REJECTED",
    "POST_REMOVED_BY_ADMIN",
    "POST_INACTIVITY_NUDGE",
    "SYSTEM_ANNOUNCEMENT",
  ],
  vetClinicSource: ["OSM", "GOOGLE_PLACES", "MANUAL"],
  adminRole: ["ADMIN", "SUPER_ADMIN"],
  moderationActionType: [
    "POST_APPROVED",
    "POST_FLAGGED",
    "POST_REMOVED",
    "POST_RESTORED",
    "USER_BANNED",
    "USER_UNBANNED",
  ],
  moderationTargetType: ["POST", "USER"],
};

export function toAvailableValues(values) {
  return values.map((value) => ({ value, label: value.replaceAll("_", " ") }));
}
